// Interfaces for payment data
export interface Payment {
  khaltiEmail: string;
  khaltiNameSurname: string;
  id: string;
  cardNumber: string;
  nameSurname: string;
  email: string;
  expDate: string;
  cvv: string;
  khaltiPhone: string; // Replaced PayPal fields with Khalti fields
}

export interface CreatePaymentRequest {
  cardNumber: string;
  nameSurname: string;
  email: string;
  expDate: string;
  cvv: string;
  khaltiPhone: string; // Khalti phone field instead of PayPal
}

export interface DeletePaymentRequest {
  id: string;
}

// Import the apiSlice (which is assumed to be a customized API slice)
import { apiSlice } from "../apiSlice/apiSlice";

// URL for payments API
const PAYMENTS_URL = "/api/payments";

// Define the paymentApiSlice for CRUD operations on payments
export const paymentApiSlice = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Create a new payment
    createPayment: builder.mutation<Payment, CreatePaymentRequest>({
      query: (body) => ({
        url: `${PAYMENTS_URL}`,
        method: "POST",
        body,
      }),
      invalidatesTags: ["Payment"],
    }),

    // Get all user payments
    getUserPayments: builder.query<Payment[], void>({
      query: () => ({
        url: `${PAYMENTS_URL}`,
        method: "GET",
      }),
      providesTags: ["Payment"],
    }),

    // Delete a payment by id
    deletePayment: builder.mutation<void, DeletePaymentRequest>({
      query: (id) => ({
        url: `${PAYMENTS_URL}/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Payment"],
    }),
  }),
});

// Export the hooks generated by the apiSlice for components to use
export const {
  useCreatePaymentMutation,
  useGetUserPaymentsQuery,
  useDeletePaymentMutation,
} = paymentApiSlice;
